MOUSEKEY_ENABLE 		= yes
VIA_ENABLE      		= no
LTO_ENABLE      		= yes
KEY_OVERRIDE_ENABLE = yes
OLED_ENABLE 				= yes
COMBO_ENABLE 				= yes
EXTRAKEY_ENABLE     = yes # Audio control and System control(+450)
CONSOLE_ENABLE      = no  # Console for debug(+400)
COMMAND_ENABLE      = no  # Commands for debug and configuration
NKRO_ENABLE         = yes # Nkey Rollover
BACKLIGHT_ENABLE    = no  # Enable keyboard backlight functionality
MIDI_ENABLE         = no  # MIDI controls
AUDIO_ENABLE        = no  # Audio output on port C6
UNICODE_ENABLE      = no  # Unicode
BLUETOOTH_ENABLE    = no  # Enable Bluetooth with the Adafruit EZ-Key HID
RGBLIGHT_ENABLE     = no  # Enable WS2812 RGB underlight.
SWAP_HANDS_ENABLE   = no